server.port: 10000

spring:
  application.name: test
  profiles:
    active: ${ACTIVE_PROFILE:default}
  config:
    import: optional:configserver:${CONFIG_URL:http://localhost:8888/config}

info:
  system: Coin Well

management:
  endpoints:
    web:
      exposure:
        include:
          - configprops
          - env
          - health
          - heapdump
          - info
          - loggers
          - mappings
          - prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"