server.port: 10000

spring:
  application.name: test
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${PROVIDER_INJINITY_ISSUER_URI:http://localhost:8100/realms/injinity}

logging:
  level:
    root: trace
    org.springframework.web: trace
    org.springframework.security: trace